### ISSUE TITLE
Your Pact library installation is out of date and we were unable to download a newer one for you: open /usr/local/lib/libpact_ffi.so: permission denied

### ISSUE THREAD

**Issue by edouard-lopez** [pact-foundation/pact-go#239] opened 2022-09-08 14:33 UTC
## Software versions

* **OS**: Ubuntu 22.04.1 LTS jammy
* **Consumer Pact library**: e.g. Pact go v0.0.8
* **Golang Version**: `go version go1.18.5 linux/amd64`
* **Golang environment**: 
```
❯ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/edouard/go/bin/"
GOCACHE="/home/edouard/.cache/go-build"
GOENV="/home/edouard/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/edouard/go/pkg/mod"
GONOPROXY="--------------"
GONOSUMDB="-------------"
GOOS="linux"
GOPATH="/home/edouard/go"
GOPRIVATE="--------------"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/9952"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/9952/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/edouard/projects/contract-testing/pact-consumer-example-for-go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4002676943=/tmp/go-build -gno-record-gcc-switches"
```

## Expected behaviour

Using `pact-go -l DEBUG install` download the latest `libpact_ffi` from https://github.com/pact-foundation/pact-reference/releases/

## Actual behaviour

Try to download `libpact_ffi-v0.3.8` while [v0.3.11](https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.3.11) is available:

```sh
❯ pact-go -l DEBUG install;
2022/09/08 16:17:48 [INFO] package libpact_ffi not found
2022/09/08 16:17:48 [INFO] downloading library from https://github.com/pact-foundation/pact-reference/releases/download/libpact_ffi-v0.3.8/libpact_ffi-linux-x86_64.so.gz to /usr/local/lib/libpact_ffi.so
2022/09/08 16:17:53 [ERROR] Your Pact library installation is out of date and we were unable to download a newer one for you: open /usr/local/lib/libpact_ffi.so: permission denied
```

## Steps to reproduce

```sh
❯ sudo rm /usr/local/lib/libpact_ffi.so
❯ go install github.com/pact-foundation/pact-go/v2@2.x.x;
```

**Comment by mefellows** [comment] 2022-09-09 00:36
> open /usr/local/lib/libpact_ffi.so: permission denied

The issue is that you can't write to that path. You could prefix with `sudo` but then you'd also need to change perms to make the file readable to all (e.g. `chmod 644 /usr/local/lib/libpact_ffi.so`).

You can change the directory of the library installation path to any of the following:

* `/opt/pact/lib`
* `/usr/local/lib`
* `/tmp`

**Comment by mefellows** [comment] 2022-09-13 07:10
I've made a minor update in the latest version (yet to release a tagged version) that will set the appropriate read permissions on the library if used with `sudo`. 

I'll update the readme as well to make it clear how to use with sudo effectively.

**Comment by onurerog** [comment] 2024-03-07 19:05
I am having this issue too. 

When I run `pact-go -l DEBUG install`  I got following.

> 2024/03/07 21:58:30 [INFO] package libpact_ffi found
> 2024/03/07 21:58:30 [DEBUG] error reading file /Users/X/.pact/pact-go.yml error:  open /Users/X/.pact/pact-go.yml: no such file or directory
> 2024/03/07 21:58:30 [INFO] no package metadata information was found, run `pact-go install -f` to correct
> 2024/03/07 21:58:30 [DEBUG] skip checking ffi version() call because FFI not loaded. This is expected when running the 'pact-go' command.

then I run `pact-go install -f` as suggested and got the following error.

> Your Pact library installation is out of date and we were unable to download a newer one for you: open /usr/local/lib/libpact_ffi.dylib: permission denied.

I tried `chmod 644 /usr/local/lib/libpact_ffi.so` and `sudo chmod -R +rwX /usr/local/lib/libpact_ffi.dylib` but they did not work. I also moved libpact_ffi.dylib file to tmp as suggested above but it did not work too.

I noticed that I have `dylib` file instead of `so` but the exception that I am getting tells me that do not have permission to dylib file as below.

Do you have any other suggestion?

**Comment by YOU54F** [comment] 2024-03-07 20:03
you will need to run run pact-go install with sudo.

it should download a dylib if you are on a mac. so files are for linux

you need to use the pact-go dl tool as it will set the required rpath on the binary

**Comment by mefellows** [comment] 2024-03-07 22:27
Closing this issue. I don't think there is anything for us to do here. Permission problems are beyond the scope of our support.

**Closed by mefellows** 2024-03-07 22:27 UTC

**Comment by bgdnvk** [comment] 2025-01-05 23:52
had the same issue
@dozer1412131 comment was very helpful
