### ISSUE TITLE
Provider verification for a tagged consumer is resulting in verification for other tagged consumers than what is requested for

### ISSUE THREAD

**Issue by sanjimoh** [pact-foundation/pact-go#98] opened 2018-10-26 09:21 UTC
## Software versions

* **OS**: RHEL 7.5
* **Consumer Pact library**: pact-go master branch
* **Provider Pact library**: pact-go master branch
* **Golang Version**: go1.11.1 linux/amd64
* **Golang environment**: 
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sanjimoh/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sanjimoh/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build487322358=/tmp/go-build -gno-record-gcc-switches"

## Actual behaviour

In my setup, I've a consumer viz. "test-consumer" publishing it's pact with consumer version "4.0.0" along with tag "sanjit-feature-branch".

When I run my provider side of test case passing consumer tag as "sanjit-feature-branch", I'm noticing the verification results are being verified and published for not only consumer tagged with "sanjit-feature-branch" but also for other consumer versions having other tags like "production" and "latest". Unfortunately this is not what I intend to achieve.

Is it a bug? or some missing settings?

For your reference, following is the command which pact-go is implicitly trying to execute for provider verification as well as publishing the verification result to pact-broker -

pact-provider-verifier http://localhost:8080/pacts/provider/test-provider-rest/consumer/test-consumer-rest/version/4.0.0 --format json --provider-base-url http://127.0.0.1:39678 --provider-states-setup-url http://127.0.0.1:39678/setup --provider_app_version 2.0.3 --publish_verification_results true

**Comment by mefellows** [comment] 2018-10-27 05:07
Can you please show me the code you are using and/or provide a reproducable code sample? There is a test broker `https://test.pact.dius.com.au` used in the builds which you could use to demonstrate.

**Comment by sanjimoh** [comment] 2018-10-28 23:53
Hi, I did some more testings and this is what I was able to conclude.

**Scenario 1:** 
              a. Consumer service (Version: 1.0.0) published it's contract with tagged "production" and "latest".
              b. Then, consumer service (Version: 2.0.0) again publishes the same contract but this time it's tagged with "sanjit-feature-branch".
              c. Then, provider service (Version: 2.0.0) tries verifying against the consumer tagged with "sanjit-feature-branch". This time provider ends up verifying with the consumer tagged with "sanjit-feature-branch" as well as "production" and "latest".

![scenario1](https://user-images.githubusercontent.com/33784301/47623715-b53c1580-db3a-11e8-9e2b-208bc05581c8.jpeg)

**Scenario 2:** 
              a. Consumer service (Version: 1.0.0) published it's contract with tagged "production" and "latest".
              b. Then, consumer service (Version: 2.0.0) makes some changes to the expected payload from provider. For example, say some attribute name in the expected response from provider. After that, it publishes the new modified contract with tag "sanjit-feature-branch".
              c. Then, provider service (Version: 2.0.0) tries verifying against the consumer tagged with "sanjit-feature-branch". This time provider verifies properly with the consumer tagged with "sanjit-feature-branch" only which is expected behavior. 

![scenario2](https://user-images.githubusercontent.com/33784301/47623726-c2590480-db3a-11e8-9e01-38c6971eeed5.jpeg)

So, from the above testing, it looks like the current behavior is that even if provider is requested to verify against a tagged consumer, it is actually going to verify itself against all the available tagged consumers if the pact is exactly the same for all the tagged consumers. [Scenario 1]
 
But, if the pacts differ between the tagged consumers, then provider verification is going to happen only against the requested tagged consumer. [Scenario 2]

Could you pl. clarify on this behavior if it is as per the design or not?

**Comment by mefellows** [comment] 2018-11-07 02:57
hi @sanjimoh sorry for the late reply, I'm going to have to dig into this further but am currently away on Holidays, so might be a few weeks before I get to the bottom of it.

The scenario 1 sounds incorrect to me at first reading. It should only fetch the tags that you're interested in if specified.

**Comment by sanjimoh** [comment] 2018-11-07 04:59
Meanwhile, I was trying to get feedback from pact-provider-verifier developers as well on this & I had been informed that this is an expected behavior and as per design. For your reference, here is the link for the same - https://github.com/pact-foundation/pact-provider-verifier/issues/29

Please share/let me know your view on it.

**Comment by mefellows** [comment] 2018-11-27 18:30
OK having a read through that makes sense. Pact Go seems to be doing the right thing here, so I will close this for now.

Thanks for the report, I can see why there was confusion.

**Closed by mefellows** 2018-11-27 18:30 UTC
Labels: triage
